# Overwrite global streamlit settings

# [global]
# dataFrameSerialization = "legacy"

[theme]
primaryColor="#e694ff"
backgroundColor="#00172b"
secondaryBackgroundColor="#0083b8"
textColor="#ffffff"
font = "sans serif"