# NB: If you overwrite the values in
# this version of the file, ensure
# you rename the file to `secrets.toml`

# authentication
API_TOKEN="SOME-API-KEY"
DASHBOARD_USER="user"
DASHBOARD_PASS="some-super-strong-password"