# NB: If you overwrite the values in
# this version of the file, ensure
# you rename the file to `secrets.toml`

# authentication
API_TOKEN="SOME-API-KEY"
DASHBOARD_USER="user"
DASHBOARD_PASS="some-super-strong-password"

# dbt specific
ACCOUNT_ID=1234

# The below maps the dbt project-ids to a human
# readable name
# You only need to keep the ones that you use,
# and can remove any you do not
[PROJECT_MAPPING]
0001="REDSHIFT - DEV"
0002="REDSHIFT - QC"
0003="REDSHIFT - PROD"
0004="BQ - DEV"
0005="BQ - QC"
0006="BQ - PROD"
0007="SNOWFLAKE - DEV"
0008="SNOWFLAKE - QC"
0009="SNOWFLAKE - PROD"

# Note that the database names should match exactly
# the way the that they are named in dbt so the dashboard
# can check the name against the metadata from the dbt run
# You only need to keep the ones that you use, and can remove
# any you do not
[PROJECT_REPO_URL_MAPPING]
redshift="https://github.com/my-org/dbt-models-redshift/tree/master/"
bigquery="https://github.com/my-org/dbt-models-bigquery/tree/master/"
snowflake="https://github.com/my-org/dbt-models-snowflake/tree/master/"